
#
hdfs-path: '/user/maria_dev'
#
download-list-of-years:
  - 2010
  - 2015
#
#download-group-of-years:
#  - 2011
#  - 2014
#
download-magnitude-over: 5
#
#download-again-historical-data: True

#hive-drop-all-tables: false