
#
hdfs-path: '/app'
#
download-list-of-years:
  - 1999
  - 1998
#
#download-group-of-years:
#  - 2011
#  - 2014
#
#download-magnitude-over: 5
#
#download-again-historical-data: True

#hive-drop-all-tables: false